In [10]:
#import numpy
import numpy as np

#numpy array
arr=np.array([1,2,3,4,5])
print(arr)
#print type of array
print(type(arr))
#numpy 2d array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
#3d array
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
#print dimension of array
print(arr3.ndim)


[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
