In [ ]:
#import numpy
import numpy as np

#numpy array
arr=np.array([1,2,3,4,5])
print(arr)
#print type of array
print(type(arr))
#numpy 2d array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
#3d array
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
#print dimension of array
print(arr3.ndim)

#array slicing
print(arr[1:4])
print(arr2[1,1])
print(arr3[1,1,1])
#negative slicing
print(arr[-3:-1])
#numpy data type
print(arr.dtype)
#numpy shape
print(arr.shape)
print(arr2.shape)
print(arr3.shape)

#RESHAPING array
arr4=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr4.reshape(4,3)
print(newarr)



[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
[2 3 4]
5
11
[3 4]
int64
(5,)
(2, 3)
(2, 2, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
